// <auto-generated />
using Calculator_Salar_WebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calculator_Salar_WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200108105311_InitialMigrationVersion1.0.")]
    partial class InitialMigrationVersion10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Calculator_Salar_WebApp.Models.GrossSalaryCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cas");

                    b.Property<long>("Cass");

                    b.Property<long>("GrossSalary");

                    b.Property<long>("NetSalary");

                    b.Property<long>("Tax");

                    b.Property<long>("TaxableBase");

                    b.HasKey("Id");

                    b.ToTable("GrossSalariesCalculator");
                });

            modelBuilder.Entity("Calculator_Salar_WebApp.Models.NetSalaryCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cas");

                    b.Property<long>("Cass");

                    b.Property<long>("GrossSalary");

                    b.Property<long>("NetSalary");

                    b.Property<long>("Tax");

                    b.Property<long>("TaxableBase");

                    b.HasKey("Id");

                    b.ToTable("NetSalariesCalculator");
                });
#pragma warning restore 612, 618
        }
    }
}
